"""add onupdate and ondelete constraint

Revision ID: 4865ef894b4b
Revises: 3443996b1232
Create Date: 2022-04-11 10:55:34.988920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4865ef894b4b'
down_revision = '3443996b1232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('camera_owners_camera_id_fkey', 'camera_owners', type_='foreignkey')
    op.create_foreign_key(None, 'camera_owners', 'cameras', ['camera_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'camera_owners', type_='foreignkey')
    op.create_foreign_key('camera_owners_camera_id_fkey', 'camera_owners', 'cameras', ['camera_id'], ['id'])
    # ### end Alembic commands ###
